# Generated by Django 3.1.7 on 2021-03-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(choices=[('01d', '1일'), ('01w', '1주'), ('01m', '1개월'), ('06m', '6개월'), ('01y', '1년')], default='01d', max_length=5)),
                ('product_oderNum', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('activation_code', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('use_yn', models.BooleanField(default=True)),
            ],
        ),
    ]
