# Generated by Django 3.1.7 on 2021-03-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='license',
            name='product_oderNum',
        ),
        migrations.AddField(
            model_name='license',
            name='license_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='product_ordrer_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
