# Generated by Django 3.1.7 on 2021-04-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_auto_20210331_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='event_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='license',
            name='use_yn',
            field=models.BooleanField(default=False),
        ),
    ]
